_______________________________
# STEP 1: EXTRACT (UPLOAD DATA)

# Mengimpor libary unutk upload file ke google colab dan menguploud file csv dari komputer

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving 2019.csv to 2019.csv

_______________________________
# STEP 2: IMPORT LIBRARY

# Mengimpor pandas untuk manipulasi data dan mengimpor numpy untuk operasi numerik

In [ ]:
import pandas as pd
import numpy as np

_______________________________
# STEP 3: CEK FILE

# Mengecek apakah file berhasil diupload

In [ ]:
import os
os.listdir()

['.config', '2019.csv', 'sample_data']

_______________________________
# STEP 4: LOAD DATA

# Membaca file CSV ke dalam DataFrame dan menampilkan 5 data pertama

In [ ]:
df = pd.read_csv('2019.csv')
df.head()

,Overall rank,Country or region,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

_______________________________
# STEP 5: DATA UNDERSTANDING

# Menampilkan jumlah baris dan kolom

In [ ]:
df.shape

(156, 9)

# Menampilkan struktur data (tipe data dan null)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 156 entries, 0 to 155
Data columns (total 9 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Overall rank                  156 non-null    int64
 1   Country or region             156 non-null    object
 2   Score                         156 non-null    float64
 3   GDP per capita                156 non-null    float64
 4   Social support                156 non-null    float64
 5   Healthy life expectancy       156 non-null    float64
 6   Freedom to make life choices  156 non-null    float64
 7   Generosity                    156 non-null    float64
 8   Perceptions of corruption     156 non-null    float64
dtypes: float64(7), int64(1), object(1)
memory usage: 11.1+ KB

# Menampilkan statistik deskriptif

In [ ]:
df.describe()

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000
mean,78.500000,5.407096,0.905147,1.208814,0.725244,0.392571,0.184846,0.110603
std,45.177428,1.113120,0.398389,0.299191,0.242124,0.143289,0.095254,0.094538
min,1.000000,2.853000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.750000,4.544500,0.602750,1.055750,0.547750,0.308000,0.108750,0.047000
50%,78.500000,5.379500,0.960000,1.271500,0.789000,0.417000,0.177500,0.085500
75%,117.250000,6.184500,1.232500,1.452500,0.881750,0.507250,0.248250,0.141250
max,156.000000,7.769000,1.684000,1.624000,1.141000,0.631000,0.566000,0.453000

# Mengecek jumlah data kosong (missing value)

In [ ]:
df.isnull().sum()

Overall rank                    0
Country or region               0
Score                           0
GDP per capita                  0
Social support                  0
Healthy life expectancy         0
Freedom to make life choices    0
Generosity                      0
Perceptions of corruption       0
dtype: int64

_______________________________
# STEP 6: TRANSFORM (DATA CLEANING)

# Mengganti nama kolom agar lebih sederhana dan konsisten

In [ ]:
df.rename(columns={
    'Overall rank': 'rank',
    'Country or region': 'country',
    'Score': 'happiness_score',
    'GDP per capita': 'gdp',
    'Social support': 'social_support',
    'Healthy life expectancy': 'life_expectancy',
    'Freedom to make life choices': 'freedom',
    'Generosity': 'generosity',
    'Perceptions of corruption': 'corruption'
}, inplace=True)

# Menampilkan hasil setelah rename

In [ ]:
df.head()

,rank,country,happiness_score,gdp,social_support,life_expectancy,freedom,generosity,corruption
0,1,Finland,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,Denmark,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,Norway,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,Iceland,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,Netherlands,7.488,1.396,1.522,0.999,0.557,0.322,0.298

# Mengecek kembali missing value

In [ ]:
df.isnull().sum()

rank               0
country            0
happiness_score    0
gdp                0
social_support     0
life_expectancy    0
freedom            0
generosity         0
corruption         0
dtype: int64

# Menghapus baris yang memiliki nilai kosong

In [ ]:
df = df.dropna()

# Mengecek jumlah data duplikat

In [ ]:
df.duplicated().sum()

np.int64(0)

# Menghapus data duplikat

In [ ]:
df = df.drop_duplicates()

____________________________________
# STEP 7: MEMBUAT DIMENSION TABLE

# Membuat tabel dimensi country (unik) dan Menambahkan primary key (ID) untuk setiap negara

In [ ]:
dim_country = df[['country']].drop_duplicates().reset_index(drop=True)
dim_country['country_id'] = dim_country.index + 1

_________________________________
# STEP 8: MEMBUAT DIMENSION YEAR

# Membuat tabel dimensi waktu (tahun)

In [ ]:
dim_year = pd.DataFrame({
    'year_id': [1],
    'year': [2019]
})

_______________________________
# STEP 9: MEMBUAT FACT TABLE

# Menggabungkan data utama dengan dimensi country, menambhakan foreign key year dan membuat fact table (hanya berisi data numerik/measure)

In [ ]:
fact = df.merge(dim_country, on='country')
fact['year_id'] = 1

fact_table = fact[[
    'country_id',
    'year_id',
    'happiness_score',
    'gdp',
    'social_support',
    'life_expectancy',
    'freedom',
    'generosity',
    'corruption'
]]

# Menampilkan hasil fact table

In [ ]:
fact_table.head()

,country_id,year_id,happiness_score,gdp,social_support,life_expectancy,freedom,generosity,corruption
0,1,1,7.769,1.340,1.587,0.986,0.596,0.153,0.393
1,2,1,7.600,1.383,1.573,0.996,0.592,0.252,0.410
2,3,1,7.554,1.488,1.582,1.028,0.603,0.271,0.341
3,4,1,7.494,1.380,1.624,1.026,0.591,0.354,0.118
4,5,1,7.488,1.396,1.522,0.999,0.557,0.322,0.298

_______________________________
# STEP 10: EXPORT DATA

# Menyimpan tabel dimensi dan fact ke file CSV

In [ ]:
dim_country.to_csv('dim_country.csv', index=False)
dim_year.to_csv('dim_year.csv', index=False)
fact_table.to_csv('fact_happiness.csv', index=False)

_______________________________
# STEP 11: DOWNLOAD FILE

# Mengunduh hasil file ke komputer

In [ ]:
files.download('dim_country.csv')
files.download('fact_happiness.csv')
files.download('dim_year.csv')